<?php

/**
 * @file
 * Contains rest_views_export.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function rest_views_export_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the rest_views_export module.
    case 'help.page.rest_views_export':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Custom plugin for Rest Export banner') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function rest_views_export_theme() {
  return [
    'rest_views_export' => [
      'render element' => 'children',
    ],
  ];
}
